import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Textbook sidebar
  textbook: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {type: 'doc', id: 'modules/module-1-ros/intro'},
      items: [
        'modules/module-1-ros/chapter-1-intro-ros/chapter-1-intro-ros',
        'modules/module-1-ros/chapter-2-nodes-communication/chapter-2-nodes-communication',
        'modules/module-1-ros/chapter-3-topics-publishers/chapter-3-topics-publishers',
        'modules/module-1-ros/chapter-4-services-actions/chapter-4-services-actions',
        'modules/module-1-ros/chapter-5-parameters-launch/chapter-5-parameters-launch',
        'modules/module-1-ros/chapter-6-packages-build/chapter-6-packages-build',
        'modules/module-1-ros/chapter-7-debugging-tools/chapter-7-debugging-tools',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Simulation)',
      link: {type: 'doc', id: 'modules/module-2-simulation/intro'},
      items: [
        'modules/module-2-simulation/chapter-8-gazebo-simulation/chapter-8-gazebo-simulation',
        'modules/module-2-simulation/chapter-9-robot-modeling/chapter-9-robot-modeling',
        'modules/module-2-simulation/chapter-10-physics-engines/chapter-10-physics-engines',
        'modules/module-2-simulation/chapter-11-unity-robotics/chapter-11-unity-robotics',
        'modules/module-2-simulation/chapter-12-advanced-scenarios/chapter-12-advanced-scenarios',
        'modules/module-2-simulation/chapter-13-sim-to-real/chapter-13-sim-to-real',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {type: 'doc', id: 'modules/module-3-ai/intro'},
      items: [
        'modules/module-3-ai/chapter-14-nvidia-isaac/chapter-14-nvidia-isaac',
        'modules/module-3-ai/chapter-15-perception-systems/chapter-15-perception-systems',
        'modules/module-3-ai/chapter-16-motion-planning/chapter-16-motion-planning',
        'modules/module-3-ai/chapter-17-robot-learning/chapter-17-robot-learning',
        'modules/module-3-ai/chapter-18-navigation-slam/chapter-18-navigation-slam',
        'modules/module-3-ai/chapter-19-manipulation-grasping/chapter-19-manipulation-grasping',
        'modules/module-3-ai/chapter-20-multi-robot/chapter-20-multi-robot',
        'modules/module-3-ai/chapter-21-ai-integration/chapter-21-ai-integration',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {type: 'doc', id: 'modules/module-4-vla/intro'},
      items: [
        'modules/module-4-vla/chapter-22-vision-language-action/chapter-22-vision-language-action',
        'modules/module-4-vla/chapter-23-embodied-ai/chapter-23-embodied-ai',
        'modules/module-4-vla/chapter-24-human-robot-interaction/chapter-24-human-robot-interaction',
        'modules/module-4-vla/chapter-25-multimodal-perception/chapter-25-multimodal-perception',
        'modules/module-4-vla/chapter-26-task-planning/chapter-26-task-planning',
        'modules/module-4-vla/chapter-27-advanced-intelligence/chapter-27-advanced-intelligence',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      items: [
        'chapter-template',
        'lab-template',
        'mcq-template',
        'section-template',
      ],
    },
  ],
};

export default sidebars;
